version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: bilten-postgres
    environment:
      POSTGRES_DB: bilten_db
      POSTGRES_USER: bilten_user
      POSTGRES_PASSWORD: bilten_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: bilten-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bilten_db
      MYSQL_USER: bilten_user
      MYSQL_PASSWORD: bilten_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: bilten-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: bilten_user
      MONGO_INITDB_ROOT_PASSWORD: bilten_password
      MONGO_INITDB_DATABASE: bilten_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: bilten-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # pgAdmin (PostgreSQL Admin Tool)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bilten-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bilten.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  # phpMyAdmin (MySQL Admin Tool)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bilten-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: bilten_user
      PMA_PASSWORD: bilten_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: unless-stopped

  # Bilten Backend API
  bilten-backend:
    build:
      context: ./bilten-backend
      dockerfile: Dockerfile
    container_name: bilten-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://bilten_user:bilten_password@postgres:5432/bilten_db
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your_jwt_secret_key_here
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  # Bilten Frontend
  bilten-frontend:
    build:
      context: ./bilten-frontend
      dockerfile: Dockerfile
    container_name: bilten-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api/v1
      REACT_APP_USE_MOCK_API: false
    ports:
      - "3000:3000"
    depends_on:
      - bilten-backend
    restart: unless-stopped

  # Bilten Scanner App
  bilten-scanner:
    build:
      context: ./bilten-scanner
      dockerfile: Dockerfile
    container_name: bilten-scanner
    environment:
      VITE_API_URL: http://localhost:3001/api/v1
    ports:
      - "3002:3002"
    depends_on:
      - bilten-backend
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
  mongodb_data:
  redis_data:
  pgadmin_data:
