# Logstash Configuration for Bilten Platform
# This configuration optimizes Logstash for structured logging

# Node configuration
node.name: bilten-logstash

# Path configuration
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
path.settings: /usr/share/logstash/config

# Pipeline configuration
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue configuration
queue.type: memory
queue.max_bytes: 1gb

# Monitoring
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["elasticsearch:9200"]

# HTTP API
http.host: "0.0.0.0"
http.port: 9600

# Logging
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# X-Pack (if available)
xpack.monitoring.enabled: false

# Config reload
config.reload.automatic: true
config.reload.interval: 3s

# Dead letter queue
dead_letter_queue.enable: false