exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('events').del();

  // Insert seed entries - Techno Events in Egypt featuring international and local artists
  await knex('events').insert([
    {
      id: 1,
      title: 'Artbat - Deep Techno Journey',
      description: 'Experience the hypnotic deep techno sounds of Artbat in an immersive night of electronic music at Cairo\'s premier venue.',
      category: 'deep-techno',
      venue_name: 'Cairo Opera House',
      venue_address: 'Gezira Island, Cairo, Egypt',
      start_date: '2025-03-15T21:00:00Z',
      end_date: '2025-03-16T03:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 2500,
      is_free: false,
      base_price: 1500.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b2d2?w=800&h=400&fit=crop',
      organizer_id: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 2,
      title: 'Amr Diab - The Plateau Concert',
      description: 'The legendary Amr Diab returns with his greatest hits and new songs in an exclusive concert at the iconic venue.',
      category: 'concert',
      venue_name: 'New Administrative Capital Arena',
      venue_address: 'New Administrative Capital, Cairo, Egypt',
      start_date: '2025-02-20T20:00:00Z',
      end_date: '2025-02-20T23:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 15000,
      is_free: false,
      base_price: 800.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800&h=400&fit=crop',
      organizer_id: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 3,
      title: 'Anyma - Melodic Techno Experience',
      description: 'Join Anyma for a spiritual journey through melodic techno rhythms and organic sounds that will move your soul.',
      category: 'melodic-techno',
      venue_name: 'Sahel Beach Club',
      venue_address: 'North Coast, Egypt',
      start_date: '2025-02-28T22:00:00Z',
      end_date: '2025-03-01T04:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 1200,
      is_free: false,
      base_price: 1000.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=400&fit=crop',
      organizer_id: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 4,
      title: 'Solomun - Organic House Sunset',
      description: 'Experience Solomun\'s signature organic house sounds as the sun sets over the Red Sea in this magical evening.',
      category: 'organic-house',
      venue_name: 'El Gouna Marina',
      venue_address: 'El Gouna, Red Sea, Egypt',
      start_date: '2025-03-10T18:00:00Z',
      end_date: '2025-03-11T01:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 1500,
      is_free: false,
      base_price: 1200.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=400&fit=crop',
      organizer_id: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 5,
      title: 'Mohamed Hamaki - Live in Alexandria',
      description: 'Egypt\'s beloved superstar Mohamed Hamaki performs his greatest hits in a spectacular concert by the Mediterranean.',
      category: 'concert',
      venue_name: 'Alexandria Opera House',
      venue_address: 'Alexandria, Egypt',
      start_date: '2025-02-15T21:00:00Z',
      end_date: '2025-02-16T00:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 3000,
      is_free: false,
      base_price: 600.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b2d2?w=800&h=400&fit=crop',
      organizer_id: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 6,
      title: 'Miss Monique - Progressive Techno Night',
      description: 'Miss Monique brings her signature progressive techno sound to Egypt for an unforgettable night of electronic music.',
      category: 'progressive-techno',
      venue_name: 'Almaza Bay',
      venue_address: 'North Coast, Egypt',
      start_date: '2025-03-20T23:00:00Z',
      end_date: '2025-03-21T06:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 2000,
      is_free: false,
      base_price: 900.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&h=400&fit=crop',
      organizer_id: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 7,
      title: 'Korolova - Melodic Techno Journey',
      description: 'Experience the enchanting melodic techno sounds of Korolova in an intimate setting under the stars.',
      category: 'melodic-techno',
      venue_name: 'Dahab Beach Resort',
      venue_address: 'Dahab, South Sinai, Egypt',
      start_date: '2025-03-25T20:00:00Z',
      end_date: '2025-03-26T02:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 800,
      is_free: false,
      base_price: 700.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=400&fit=crop',
      organizer_id: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 8,
      title: 'Adriatique - Deep House Sunset',
      description: 'Adriatique brings their signature deep house sound to the Red Sea for a magical sunset session.',
      category: 'deep-house',
      venue_name: 'Hurghada Marina',
      venue_address: 'Hurghada, Red Sea, Egypt',
      start_date: '2025-04-05T17:00:00Z',
      end_date: '2025-04-05T23:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 1000,
      is_free: false,
      base_price: 800.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=400&fit=crop',
      organizer_id: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 9,
      title: 'CamelPhat - Progressive House Night',
      description: 'CamelPhat delivers their chart-topping progressive house hits in an electrifying performance.',
      category: 'progressive-house',
      venue_name: 'Cairo Festival City',
      venue_address: 'New Cairo, Egypt',
      start_date: '2025-04-12T22:00:00Z',
      end_date: '2025-04-13T04:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 3000,
      is_free: false,
      base_price: 1100.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=400&fit=crop',
      organizer_id: 4,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      id: 10,
      title: 'Monolink - Live Techno Experience',
      description: 'Monolink combines live guitar and vocals with melodic techno for a unique and unforgettable performance.',
      category: 'live-techno',
      venue_name: 'Zamalek Art Center',
      venue_address: 'Zamalek, Cairo, Egypt',
      start_date: '2025-04-20T21:00:00Z',
      end_date: '2025-04-21T02:00:00Z',
      timezone: 'Africa/Cairo',
      max_attendees: 1500,
      is_free: false,
      base_price: 950.00,
      status: 'published',
      cover_image_url: 'https://images.unsplash.com/photo-1571266028243-d220c9c3b2d2?w=800&h=400&fit=crop',
      organizer_id: 2,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Reset sequence
  await knex.raw('SELECT setval(\'events_id_seq\', (SELECT MAX(id) FROM events))');
};